# VoiceCall use case for Nothing Phone (1)
# EAR = top amp (earpiece), SPK = bottom amp (loudspeaker)

SectionVerb {
	EnableSequence [
		cset "name='PRI_MI2S_RX Voice Mixer VoiceMMode1' 1"
		cset "name='VoiceMMode1 Capture Mixer TX_CODEC_DMA_TX_3' 1"
	]

	DisableSequence [
		cset "name='PRI_MI2S_RX Voice Mixer VoiceMMode1' 0"
		cset "name='VoiceMMode1 Capture Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value.TQ "VoiceCall"
}

SectionDevice."Earpiece" {
	Comment "Earpiece Playback"

	EnableSequence [
		cset "name='SPK Playback Switch' off"
		cset "name='EAR Playback Switch' on"
		cset "name='EAR Profile Set' receiver"
		exec "/run/current-system/sw/bin/systemctl --user start voice-keeper-play@Earpiece.service"
	]

	DisableSequence [
		exec "/run/current-system/sw/bin/systemctl --user stop voice-keeper-play@Earpiece.service"
		cset "name='EAR Profile Set' Default"
		cset "name='SPK Playback Switch' on"
	]

	Value {
		PlaybackChannels 1
		PlaybackPriority 300
		PlaybackPCM "hw:${CardId},5"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker Playback"

	EnableSequence [
		cset "name='EAR Playback Switch' on"
		cset "name='SPK Playback Switch' on"
		cset "name='EAR Profile Set' Default"
		cset "name='SPK Profile Set' speaker"
		exec "/run/current-system/sw/bin/systemctl --user start voice-keeper-play@Speaker.service"
	]

	DisableSequence [
		exec "/run/current-system/sw/bin/systemctl --user stop voice-keeper-play@Speaker.service"
		cset "name='SPK Profile Set' Default"
	]

	Value {
		PlaybackChannels 1
		PlaybackPriority 250
		PlaybackPCM "hw:${CardId},5"
	}
}

SectionDevice."Mic1" {
	Comment "Bottom Microphone"

	Include.wcdmice.File "/codecs/wcd938x/AnalogMic1EnableSeq.conf"
	Include.wcdmicd.File "/codecs/wcd938x/AnalogMic1DisableSeq.conf"
	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/SoundwireMic0EnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"

	EnableSequence [
		cset "name='TX_DEC0 Volume' 84"
		exec "/run/current-system/sw/bin/systemctl --user start voice-keeper-capture.service"
	]

	DisableSequence [
		exec "/run/current-system/sw/bin/systemctl --user stop voice-keeper-capture.service"
	]

	Value {
		CaptureChannels 1
		CapturePriority 200
		CapturePCM "hw:${CardId},5"
		CaptureMixer "default:${CardId}"
		CaptureMixerElem "ADC1"
		CaptureVolume "ADC1 Volume"
		CaptureSwitch "ADC1 Switch"
	}
}
